---
- name: "Create a new database"
  community.mysql.mysql_db:
    name: "{{ MYSQL_DB_NAME }}"
    state: "present"
    login_user: "root"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_unix_socket: "/run/mysqld/mysqld.sock"