---
- block:
    - name: "Install privoxy"
      ansible.builtin.include_tasks: "install.yml"
  tags: "install"

- block:
    - name: "Configure privoxy"
      ansible.builtin.include_tasks: "configure.yml"
  tags: "configure"

- block:
    - name: "Remove privoxy"
      ansible.builtin.include_tasks: "remove.yml"
  tags: "remove"