---
- block:
    - name: "Install supervisor"
      ansible.builtin.include_tasks: "install.yml"
  tags: "install"

- block:
    - name: "Configure supervisor"
      ansible.builtin.include_tasks: "configure.yml"
      tags:
        - conf_file
  tags: "configure"

- block:
    - name: "Remove supervisor"
      ansible.builtin.include_tasks: "remove.yml"
  tags: "remove"