---
- name: "Stop and disable supervisor service"
  ignore_errors: "yes"
  ansible.builtin.service:
    name: "supervisor"
    state: "stopped"
    enabled: "false"

- name: "Remove supervisor via apt"
  ansible.builtin.apt:
    name: "supervisor"
    state: "absent"
    purge: "true"
    autoremove: "true"
  register: "apt_action"
  retries: "50"
  until: "apt_action is success or ('E: Could not get lock /var/lib/dpkg/lock-frontend' not in apt_action.msg and '/var/lib/dpkg/lock-frontend' not in apt_action.msg)"

- name: "Remove config and log files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "{{ SUPERVISOR_LOG_PATH }}"
    - "{{ SUPERVISOR_CONFIG_PATH }}"
    
