---
- name: "Stop node_exporter service"
  ansible.builtin.systemd: # noqa ignore-errors
    name: "node_exporter.service"
    state: "stopped"
  ignore_errors: "true"

- name: "Remove node_exporter binary and systemd unit"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "{{ NODE_EXPORTER_BINARY_INSTALL_DIR }}/node_exporter"
    - "{{ NODE_EXPORTER_SERVICE_FILE_PATH}}/node_exporter.service"

- name: "Remove the node_exporter system user"
  ansible.builtin.user:
    name: "{{ NODE_EXPORTER_SYSTEM_USER }}"
    force: "true"
    state: "absent"

- name: "Remove node_exporter system group"
  ansible.builtin.group:
    name: "{{ NODE_EXPORTER_SYSTEM_GROUP  }}"
    state: "absent"
