---
- name: "install | repo gpg key"
  ansible.builtin.apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ MONGODB_VERSION }}.asc"

- name: "Add mongodb repository"
  ansible.builtin.apt_repository:
    filename: "/etc/apt/sources.list.d/mongodb-org-{{ MONGODB_VERSION }}"
    repo: "deb https://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/{{ MONGODB_VERSION }} multiverse"
    state: "present"
    update_cache: "yes"
  register: "apt_action"
  retries: "50"
  until: "apt_action is success or ('E: Could not get lock /var/lib/dpkg/lock-frontend' not in apt_action.msg and '/var/lib/dpkg/lock-frontend' not in apt_action.msg)"

- name: "Install MongoDB"
  ansible.builtin.package:
    name: "mongodb-org"
    state: "present"
    update_cache: "yes"
  register: "apt_action"
  retries: "50"
  until: "apt_action is success or ('E: Could not get lock /var/lib/dpkg/lock-frontend' not in apt_action.msg and '/var/lib/dpkg/lock-frontend' not in apt_action.msg)"

- name: "Ensure MongoDB is started and enabled at boot."
  ansible.builtin.service:
    name: "mongod"
    state: "started"
    enabled: "yes"

- name: "Install python3-pip "
  ansible.builtin.package:
    name: "python3-pip"
    state: "present"

- name: "Install | pymongo"
  ansible.builtin.pip:
    name: "pymongo"
    executable: "pip3"