---
- block:
    - name: "Install docker"
      ansible.builtin.include_tasks: "install.yml"
  tags: "install"

- block: 
    - name: "Remove docker"
      ansible.builtin.include_tasks: "remove.yml"
  tags: "remove"