---
- name: "Install logstash"
  block:
  - name: "Install apt package requirements"
    ansible.builtin.apt:
      name: "{{ LOGSTASH_REQUIREMENTS }}"
      state: "present"
      update_cache: "yes"
    register: "apt_action"
    retries: "5"
    until: "apt_action is success or ('E: Could not get lock /var/lib/dpkg/lock-frontend' not in apt_action.msg and '/var/lib/dpkg/lock-frontend' not in apt_action.msg)"

  - name: "Add ELK apt key."
    ansible.builtin.apt_key:
      url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
      id: "46095ACC8548582C1A2699A9D27D666CD88E42B4"
      state: "present"

  - name: "Add ELK repository."
    ansible.builtin.apt_repository:
      repo: 'deb https://artifacts.elastic.co/packages/{{ ELK_VERSION_FAMILY }}/apt stable main'
      state: "present"

  - name: "Install logstash package"
    ansible.builtin.apt:
      name: "logstash={{ LOGSTASH_VERSION }}"
      state: "present"
      update_cache: "yes"
    register: "apt_action"
    retries: "5"
    until: "apt_action is success or ('E: Could not get lock /var/lib/dpkg/lock-frontend' not in apt_action.msg and '/var/lib/dpkg/lock-frontend' not in apt_action.msg)"

  when: "inventory_hostname in groups['logstash']"