{
 "title": "Elasticsearch Exporter",
 "description": "A quickstart to setup the Prometheus Elasticsearch Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(elasticsearch_cluster_health_status, job)"
   },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_indices_docs{job=\"$job\"},cluster)"
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{job=\"$job\", cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\",color=\"yellow\"}==1)+2"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"} ) / count (elasticsearch_process_cpu_percent{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"} )"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}) / sum (elasticsearch_jvm_memory_max_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents count on node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "timeseries",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_docs_deleted{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_os_load1{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}/elasticsearch_filesystem_data_size_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: sent "
    },
    {
     "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total translog operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_operations{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total translog size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_size_in_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tripped for breakers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "elasticsearch_breakers_tripped{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{name}}: {{breaker}}"
      }
     ]
    },
    {
     "title": "Estimated size in bytes of breaker",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "elasticsearch_breakers_estimated_size_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{name}}: {{breaker}}"
      },
      {
       "expr": "elasticsearch_breakers_limit_size_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{name}}: limit for {{breaker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Operations  rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_tota{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations rejected",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_rejected_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Field data memory size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Evictions from filter cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_filter_cache_evictions{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count of index segments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}