{
 "title": "Nginx Exporter Full",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "datasource", "query": "prometheus" },
   {
    "name": "Host",
    "query": {
     "query": "label_values({job=\"nginx-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $Host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$Host\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=\"$Host\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=\"$Host\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$Host\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$Host\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$Host\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$Host\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=\"$Host\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  },
  { "title": "Metrics By Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, sum(\n        rate(\n            nginx_http_response_time_seconds_hist_bucket\n            {\n                instance=\"$Host\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(\n    0.90, sum(\n        rate(\n            nginx_http_response_time_seconds_hist_bucket\n            {\n                instance=\"$Host\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n    0.50, sum(\n        rate(\n            nginx_http_response_time_seconds_hist_bucket\n            {\n                instance=\"$Host\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{instance=\"$Host\"}[1m])) by(status)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_count{instance=\"$Host\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_sum{instance=\"$Host\"}[5m]))/sum(rate(nginx_http_response_time_seconds_count{instance=\"$Host\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{instance=\"$Host\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status code responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{status!~\"[4-5].*\",instance=\"$Host\"}[1m])) / sum(rate(nginx_http_response_count_total{instance=\"$Host\"}[1m]))",
     "legendFormat": "{{ instance }} non-4|5xx responses"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"[4-5].*\",instance=\"$Host\"}[1m])) / sum(rate(nginx_http_response_count_total{instance=\"$Host\"}[1m]))",
     "legendFormat": "{{ instance }} 4|5xx responses"
    }
   ]
  }
 ]
}