{
 "title": "PHP-FPM Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "datasource", "query": "prometheus" },
   {
    "name": "Host",
    "query": {
     "query": "label_values({job=\"phpfpm-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP-FPM Status for $Host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "php_fpm_up{instance=\"$Host\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "The date and time FPM has started or reloaded. Reloading PHP-FPM",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-(php_fpm_start_time_seconds{instance=\"$Host\"})",
     "legendFormat": "{{instance}} PHP-FPM Service Uptime"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active processes",
   "type": "timeseries",
   "description": "The number of active processes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "php_fpm_active_processes{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Active processes"
    }
   ]
  },
  {
   "title": "Idle processes",
   "type": "timeseries",
   "description": "The number of idle processes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "php_fpm_idle_processes{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Idle processes"
    }
   ]
  },
  {
   "title": "Max active processes",
   "type": "timeseries",
   "description": "The maximum number of active processes since FPM has started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "php_fpm_max_active_processes{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Max Active Processes"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "timeseries",
   "description": "The number of idle + active processes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "php_fpm_total_processes{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Process Count"
    }
   ]
  },
  {
   "title": "Accepted Connections Rate",
   "type": "timeseries",
   "description": "Total number of accepted connections as irate in a range of 5 minutes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "irate(php_fpm_accepted_connections_total{instance=~\"$Host\"}[5m])",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Max children reached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "php_fpm_max_children_reached{instance=\"$Host\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "php_fpm_active_processes{instance=\"$Host\"} / php_fpm_max_active_processes{instance=\"$Host\"}",
     "legendFormat": "{{instance}} Pool Usage"
    }
   ]
  },
  {
   "title": "Listen Queue",
   "type": "timeseries",
   "description": "The number of request in the queue of pending connections. If this number is non-zero, then you better increase number of process FPM can spawn.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "php_fpm_listen_queue{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Listen Queue"
    }
   ]
  },
  {
   "title": "Listen Queue Lengtht",
   "type": "timeseries",
   "description": "The size of the socket queue of pending connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "php_fpm_listen_queue_length{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Listen Queue Lengtht"
    }
   ]
  },
  {
   "title": "Listen Queue Max Connections",
   "type": "timeseries",
   "description": "The maximum number of requests in the queue of pending connections since FPM has started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "php_fpm_max_listen_queue{instance=\"$Host\"}",
     "legendFormat": "{{instance}} PHP-FPM Listen Queue Max Connections"
    }
   ]
  }
 ]
}